blank_issues_enabled: false
contact_links:
  - name: Anartree documentation
    url: https://github.com/adaltas/anartree
    about: Check out the Anartree documentation for answers to common questions.
